name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v3

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v2

    - name: Install Libraries
      run: luarocks install luafilesystem

    - name: Run build.lua
      run: lua build.lua
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      if: success()
      with:
        name: Hyper.tpkg
        path: /home/runner/work/Hyper/Hyper/Hyper.tpkg
