name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v3

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v2

    - name: Install Libraries
      run: luarocks install luafilesystem

    - name: Run build.lua
      run: lua build.lua
